service: my-express-application

provider:
  name: azure
  location: Central US

plugins:
  - serverless-azure-functions

functions:
  app:
    handler: index.handler
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
